apiVersion: v2
appVersion: "1.1.1"
description: A Helm chart for Kubernetes
name: alias-oracle
version: 1.1.1

dependencies:
  - name: mariadb
    version: 9.5.1
    condition: mariadb.enabled
    repository: https://charts.bitnami.com/bitnami
