{{- if .Values.imagePullCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alias-oracle.name" . }}-cred
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "alias-oracle.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
