apiVersion: v1
kind: Service
metadata:
  name: {{ include "alias-oracle.fullname" . }}
  labels:
{{ include "alias-oracle.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.env.alsApiListenPort }}
      targetPort: alsapiport
      protocol: TCP
      name: alsapiport
    - port: {{ .Values.env.adminApiListenPort }}
      targetPort: adminapiport
      protocol: TCP
      name: adminapiport
  selector:
    app.kubernetes.io/name: {{ include "alias-oracle.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
